name: ChatFilter
version: '1.0.0'
main: org.turbojax.ChatFilter
api-version: '1.21'
authors: [TurboJax07, duff_mans_jnr]
website: modrinth.com/plugins/ChatFilter

commands:
  chatfilter:
    description:
    aliases:
      filter
    usage: "/<command> [help,add,remove,list,reload]"

permissions:
  chatfilter.notify:
    description: "Players with this permission will be notified when a message contains blocked language."
    default: op
