name: ChatFilter
version: '1.0.0'
main: org.turbojax.ChatFilter
api-version: '1.21'
authors: [TurboJax07, duff_mans_jnr]
website: modrinth.com/plugins/ChatFilter

commands:
  chatfilter:
    description:
    aliases:
      filter
    usage: "/<command> [help,add,remove,list,reload]"

permissions:
  chatfilter.notify:
    description: "Players with this permission will be notified when a message contains blocked language."
    default: op
  chatfilter.command.add:
    description: "Players with this permission are able to use the command \"/chatfilter add\"."
    default: op
  chatfilter.command.remove:
    description: "Players with this permission are able to use the command \"/chatfilter remove\"."
    default: op
  chatfilter.command.list:
    description: "Players with this permission are able to use the command \"/chatfilter list\"."
    default: op
  chatfilter.command.reload:
    description: "Players with this permission are able to use the command \"/chatfilter reload\"."
    default: op
  chatfilter.command.help:
    description: "Players with this permission are able to use the command \"/chatfilter help\"."
    default: true
  chatfilter.command.version:
    description: "Players with this permission are able to use the command \"/chatfilter version\"."
    default: op
  chatfilter.command.save:
    description: "Players with this permission are able to use the command \"/chatfilter save\"."
    default: op
  chatfilter.bypass:
    description: "Allows players to bypass both the rename and chat filters."
    default: false
    children:
      chatfilter.bypass.anvil: false
      chatfilter.bypass.chat: false
